Hw02 express
bokhvalov/nodejs-rest-api pull request #1
Opened 2023-01-23 02:49 UTC by bokhvalov

Please check

2023-01-23 18:34 UTC, Eastvarga requested changes
Є зауваження, валидація та робота з методом масиву

2023-01-23 18:34 UTC, Eastvarga commented on models/contacts.js
> +  for (let i = 0; i < parsedContacts.length; i++) {
WTF?
використайте метод масиву map((elem,index,selfArr)=>{}) котрий проходить по масиву та повертає як елемент у новий масив те що повертає калбек функція. Ви зможете при співпадінні айдішника повернути оновлений елемент (контакт) та записати його у змінну оголошену раніше, наприклад. Та повернути цю хмінну як результат, якщо вона не пуста, попередньо записавши оновлений масив у файл.
Зробіть це - вміння працювати з методами масиву є майже основою, бо з масивами завжди прийдеться працювати

2023-01-23 18:34 UTC, Eastvarga commented on routes/api/contacts.js
> +const newContactSchema = Joi.object({
Виокремьте валідацію у модуль

2023-01-23 18:34 UTC, Eastvarga commented on routes/api/contacts.js
> +  name: Joi.string().alphanum().min(3).max(15),
чому немає методу .optional() для усіх полей?

2023-01-23 18:34 UTC, Eastvarga commented on routes/api/contacts.js
> +});
метод .min(1) дасть можливість валідації повертати помилку, коли відсутні усі опціональні поля

2023-01-23 18:34 UTC, Eastvarga commented on routes/api/contacts.js
> +  res.json(data);
забули status(200)

2023-01-23 18:34 UTC, Eastvarga commented on routes/api/contacts.js
> +  const { error, value } = newContactSchema.validate(req.body);
Це треба винести до мідлвара валідації

2023-01-23 18:34 UTC, Eastvarga commented on routes/api/contacts.js
> +  if (!Object.keys(req.body).length) {
Звідки Ви все це зкопіювали?
У вас є валідація, тому все це реалізувати через методи валідації можна!!!

2023-01-24 01:29 UTC, bokhvalov commented on models/contacts.js
> +  for (let i = 0; i < parsedContacts.length; i++) {
Я вмію працювати з масивами і добре знаю що таке map, але вважаю що він тут не буде оптимальним вирішеням задачі.

У цьому випадку фор використаний для переривання проходження по масиву, після знаходження потрібного контакту, адже якщо потрібний контакт буде першим у списку, немає потреби проходитись по тисячях наступних контактів.

2023-01-24 01:31 UTC, bokhvalov commented on routes/api/contacts.js
> +  res.json(data);
чи статус 200 не йде за змовчуванням?

2023-01-24 01:36 UTC, bokhvalov commented on routes/api/contacts.js
> +  if (!Object.keys(req.body).length) {
.... не копіював, а зробив повернення помилки у випадку відсутності body...

ок, подивлюсь валідацію церез joi

2023-01-24 07:30 UTC, Eastvarga commented on models/contacts.js
> +  for (let i = 0; i < parsedContacts.length; i++) {
Почитайте "Грокая алгоритми" - зрозумієте як оцінюється складність алгоритмів. 
В данному випадку вона однакова що у циклу фор, що у методу мап. Тільки метод мап більш оптимізован. А вміння працювати з методами масиву завжди важливо, не бійтеся їми користуватись, бо практика розвиває вміння.

2023-01-24 07:33 UTC, Eastvarga approved these changes

2023-01-24 07:33 UTC, merged