Hw05 avatars
bokhvalov/nodejs-rest-api pull request #4
Opened 2023-02-25 15:58 UTC by bokhvalov

2023-02-26 10:17 UTC, Eastvarga requested changes
Є зауваження

2023-02-26 10:17 UTC, Eastvarga commented on app.js
> +app.use("/avatars", avatarsRouter);
чому окремий раут якщо за умовами раут повинен бути у users, тоб-то /api/users/avatars

2023-02-26 10:17 UTC, Eastvarga commented on controllers/avatarsController.js
> +  res.json(avatarURL);
**res.json({ avatarURL });** ось в цьому випадку необхідно віддавати об'єкт з полем avatarURL

2023-02-26 10:17 UTC, Eastvarga commented on controllers/contactsController.js
>      );
це навіщо? Ви шукаєте по цим параметрам - навіщо перевіряти чи вірно повернула Вам база данні? - Як запитали так вона й поверне

2023-02-26 10:17 UTC, Eastvarga commented on controllers/usersController.js
> +  console.log(avatarURL);
консоль до чого тут?

2023-02-26 10:17 UTC, Eastvarga commented on routes/avatars.js
> +);
WTF?
так статика не підключається
app.use(express.static("public")); - і все - де цей код вставити вже самі знайдіть, почитайте уважно матеріали та лекції передивіться, бо зараз Ви не зовсім розумієте що таке статика та як її встановити на сервер (не раут)

2023-02-26 10:17 UTC, Eastvarga commented on services/avatarService.js
> +  return newImgPath;
невірна логіка - 
Ви повинні зберігти файл у темп - це є
далі змінити ім'я файлу та перемістити його до теки "public/avatars" - **цього не бачу.**
далі згенерувати url для файлу const newImgPath = "/avatars/avatar-" + userId + "." + imgExtension; - це щось схоже на відносний шлях -(+)
зберігти url  у юзері - теж начбто є
Ви загубили саме важливе - перенесення завантаженого файлу до статичної теки!

2023-02-26 17:51 UTC, bokhvalov commented on app.js
> +app.use("/avatars", avatarsRouter);
<img width="1204" alt="image" src="https://user-images.githubusercontent.com/103508644/221427389-25957dda-fe24-4326-8e56-1e59af9305da.png">
Ось чому

2023-02-27 17:27 UTC, bokhvalov commented
Прошу допомогти з перевіркою токену у тестах
- userControllerTest.js строка 55

не можу знайти спосіб як з mRes витягнути значення токену і вкинути його до функції jwt.verify

2023-02-27 17:39 UTC, Eastvarga commented on app.js
> +app.use("/avatars", avatarsRouter);
Не вірно! З якого дива статична тека зумовлює окремий раут?
Перечитайте уважно матеріали, та відео лекцію передивіться уважно.

2023-02-27 18:08 UTC, Eastvarga requested changes
Є зауваження що до строки для файлу

2023-02-27 18:08 UTC, Eastvarga commented on services/avatarService.js
> +  const newImgPath = "public/avatars/avatar-" + userId + "." + imgExtension;
якщо ця строка використовується для операцій з файлом у файловій системі - краще використати модуль path  const newImgPath = path.join("public","avatars",\`avatar-${userId }.${imgExtension}`);

2023-02-27 18:08 UTC, Eastvarga commented on services/avatarService.js
> +  return '/avatars/avatar-' + userId + "." + imgExtension;
Так, це вийде відносний шлях урл але
\`/avatars/avatar-${userId }.${imgExtension}` таке формування строки ліпше

2023-02-27 18:08 UTC, Eastvarga commented on __tests__/userControllerTest.js
> +    expect(mRes.json).toHaveBeenCalledWith({
Проблема в тому - що Ви не знаєте що робить json(body) - у відповіді - ця функція стрінгує тіло відповіді та записує його у body -  Логін як результат успіху (а ми саме це емулюємо) записує у відповідь тіло певного зразку - отже функція  json: jest.fn(), повинна записати той об'єкт що отримає у mRes.body - і перевіряти Ви повинні що потрапить у mRes.body та чи буде це відповідати очікуваному тілу відповіді.
 json: jest.fn() - ви повинні реалізувати цю функцію

2023-02-27 19:31 UTC, Eastvarga approved these changes

2023-02-27 19:31 UTC, merged